### ISSUE TITLE
Syntax error callback(null,{)}

### ISSUE THREAD

**Issue by chrisspiegl** [jleonard/Async-Snippets#2]
I just tried this snippet and noticed that there is some weird syntax in the snippets.

I used the async_series snippet and it inserted the code but it is not valid code. The error is in the callback: `callback(null,{)}` (the closing bracket is not the last thing but inside the curly brackets.

Additionally the `;` are missing for the callbacks.

Is this intention or a mistake?

Note: I am using Sublime Text 3

**Comment by jleonard** [comment]
Thanks for catching this. There was an issue with the way the curly braces were being escaped. I've fixed the issue and it should be reflected in Sublime Text once you've restarted the app.

**Comment by chrisspiegl** [comment]
Looks good thanks.
